<?php

namespace Reducktion\Socrates\Core\Yugoslavia;

class YugoslaviaRegions
{

    public static $regions = [
            '01' => 'foreigner in Bosnia and Herzegovina',
            '02' => 'foreigners in Montenegro',
            '03' => 'foreigners in Croatia',
            '04' => ' foreigners in Macedonia',
            '05' => 'foreigners in Slovenia',
            '06' => 'foreigners in Central Serbia',
            '07' => 'foreigners in Vojvodina',
            '08' => 'foreigners in Kosovo',
            '09' => 'naturalized citizen with no republican citizenship',
            '10' => 'Banja Luka - Bosnia and Herzegovina',
            '11' => 'Bihać - Bosnia and Herzegovina',
            '12' => 'Doboj - Bosnia and Herzegovina',
            '13' => 'Goražde - Bosnia and Herzegovina',
            '14' => 'Livno - Bosnia and Herzegovina',
            '15' => 'Mostar - Bosnia and Herzegovina',
            '16' => 'Prijedor - Bosnia and Herzegovina',
            '17' => 'Sarajevo - Bosnia and Herzegovina',
            '18' => 'Tuzla - Bosnia and Herzegovina',
            '19' => 'Zenica - Bosnia and Herzegovina',
            '20' => 'Montenegro',
            '21' => 'Podgorica, Danilovgrad, Kolašin - Montenegro',
            '22' => 'Bar, Ulcinj - Montenegro',
            '23' => 'Budva, Kotor, Tivat - Montenegro',
            '24' => 'Herceg Novi - Montenegro',
            '25' => 'Cetinje - Montenegro',
            '26' => 'Nikšić, Plužine, Šavnik - Montenegro',
            '27' => 'Berane, Rožaje, Plav, Andrijevica - Montenegro',
            '28' => 'Bijelo Polje, Mojkovac - Montenegro',
            '29' => 'Pljevlja, Žabljak - Montenegro',
            '30' => 'Osijek, Slavonia region - Croatia',
            '31' => 'Bjelovar, Virovitica, Koprivnica, Pakrac, Podravina region - Croatia',
            '32' => 'Varaždin, Međimurje region - Croatia',
            '33' => 'Zagreb - Croatia',
            '34' => 'Karlovac, Kordun region - Croatia',
            '35' => 'Gospić, Lika region - Croatia',
            '36' => 'Rijeka, Pula, Gorski kotar, Istria and Croatian Littoral regions - Croatia',
            '37' => 'Sisak, Banovina region - Croatia',
            '38' => 'Split, Zadar, Šibenik, Dubrovnik, Dalmatia region - Croatia',
            '39' => 'Hrvatsko Zagorje and mixed - Croatia',
            '40' => 'Macedonia',
            '41' => 'Bitola - Macedonia',
            '42' => 'Kumanovo - Macedonia',
            '43' => 'Ohrid - Macedonia',
            '44' => 'Prilep - Macedonia',
            '45' => 'Skopje - Macedonia',
            '46' => 'Strumica - Macedonia',
            '47' => 'Tetovo - Macedonia',
            '48' => 'Veles - Macedonia',
            '49' => 'Štip - Macedonia',
            '50' => 'Slovenia',
            '60' => 'Temporary residence',
            '61' => 'Temporary residence',
            '62' => 'Temporary residence',
            '63' => 'Temporary residence',
            '64' => 'Temporary residence',
            '65' => 'Temporary residence',
            '66' => 'Temporary residence',
            '67' => 'Temporary residence',
            '68' => 'Temporary residence',
            '69' => 'Temporary residence',
            '70' => 'Serbian citizens registered abroad at a Serbian diplomatic/consular post - Serbia',
            '71' => 'Belgrade region (City of Belgrade) - Central Serbia',
            '72' => 'Šumadija and Pomoravlje regions (Šumadija District and Pomoravlje District) - Central Serbia',
            '73' => 'Niš region (Nišava District, Pirot District and Toplica District) - Central Serbia',
            '74' => 'Southern Morava region (Jablanica District and Pčinja District) - Central Serbia',
            '75' => 'Zaječar region (Zaječar District and Bor District) - Central Serbia',
            '76' => 'Podunavlje region (Podunavlje District and Braničevo District) - Central Serbia',
            '77' => 'Podrinje and Kolubara regions (Mačva District and Kolubara District) - Central Serbia',
            '78' => 'Kraljevo region (Raška District, Moravica District and Rasina District) - Central Serbia',
            '79' => 'Užice region (Zlatibor District) - Central Serbia',
            '80' => 'Novi Sad region (South Bačka District) - Serbian province of Vojvodina',
            '81' => 'Sombor region (West Bačka District) - Serbian province of Vojvodina',
            '82' => 'Subotica region (North Bačka District) - Serbian province of Vojvodina',
            '84' => 'Kikinda region (North Banat District) - Serbian province of Vojvodina',
            '85' => 'Zrenjanin region (Central Banat District) - Serbian province of Vojvodina',
            '86' => 'Pančevo region (South Banat District) - Serbian province of Vojvodina',
            '87' => 'Vršac region (South Banat District) - Serbian province of Vojvodina',
            '88' => 'Ruma region (part of Syrmia District) - Serbian province of Vojvodina',
            '89' => 'Sremska Mitrovica region (part of Syrmia District) - Serbian province of Vojvodina',
            '90' => 'Kosovo',
            '91' => 'Priština region (Kosovo District) - Serbian province of Kosovo',
            '92' => 'Kosovska Mitrovica region (Kosovska Mitrovica District) - Serbian province of Kosovo',
            '93' => 'Peć region (part of Peć District) - Serbian province of Kosovo',
            '94' => 'Đakovica region (part of Peć District) - Serbian province of Kosovo',
            '95' => 'Prizren region (Prizren District) - Serbian province of Kosovo',
            '96' => 'Gnjilane region (Kosovo-Pomoravlje District) - Serbian province of Kosovo',
            '97' => 'Kosovo',
            '98' => 'Kosovo',
            '99' => 'Kosovo',
        ];

}